Help commands are hidden for non-authorized users
codeRIT/mentorbot pull request #18
Opened 2020-12-26 18:23 UTC by colbygallup

Closes #8

2021-01-16 19:39 UTC, Madrugaur requested changes
Just a thought: Maybe it would be a good idea to reference the Role that a Topic has inside the Topic class as local variable. I.e 
public Topic {
    private final Role role;
etc..
} 
Something like this would cut down on the amount of searching you would need to do.

2021-01-21 06:42 UTC, peterkos approved these changes
LGTM, also, any plans to add docs for some methods? I'll admit, i'm a bit spoiled by authbot 😛

2021-01-21 06:42 UTC, peterkos commented on src/main/java/listeners/MainEventListener.java
> +            embedBuilder.addField("$ready <topic> (mentor only)", "Retrieve the next person from the queue.", false);
I like how the role is specified in the command name!

2021-01-22 23:40 UTC, colbygallup commented
@peterkos I'll definitely be adding more documentation to the code soon

2021-01-23 00:03 UTC, colbygallup commented
I replaced the `ArrayList<Topic>` in the Server class with a `HashMap<String, Topic>` with the topic name as a key. This should make searching for a topic by name a lot faster (O(n) -> O(1)). I also stored the Role for a Topic inside the Topic object itself, as @Madrugaur suggested.

2021-01-30 18:00 UTC, merged